### ISSUE TITLE
NEP-43: Change On Community Node NEW Unlocking Period

### ISSUE THREAD

**Issue by arisac** [newtonproject/NEPs#43]
https://neps.newtonproject.org/neps/nep-43/

Future discussion for NEP-43 under this issue

**Comment by xujizhe** [comment]
NEP-43 will make the community node mining rules more simple and clear, and more potential NEW liquidities for the Newton ecosystem. Suggest to implement NEP-43 soon.

**Comment by evanliuchina** [comment]
+1

**Comment by arisac** [comment]
> NEP-43 will make the community node mining rules more simple and clear, and more potential NEW liquidities for the Newton ecosystem. Suggest to implement NEP-43 soon.

@weixuefeng @VieYang can we come up with a date when this can be implemented as soon as possible?

**Comment by xujizhe** [comment]
> > NEP-43 will make the community node mining rules more simple and clear, and more potential NEW liquidities for the Newton ecosystem. Suggest to implement NEP-43 soon.
> 
> @weixuefeng @VieYang can we come up with a date when this can be implemented as soon as possible?

Thank you Arisac for writing this proposal.

**Comment by xujizhe** [comment]
Thank you Arisac for writing this proposal.

**Comment by zhouxiqiao** [comment]
**Agree.**

With a more open and richer Newton ecosystem, the community node/vote mining rules should be more flexible for every participant. Remove/reduce restrictive rules could lower the barriers to all potential Newton community members and provide better NEW liquidities for DApps on NewChain.

I think ideally the community node/vote minging rules will be no minimum amount requirement and no unlocking period(probably at least 1 day to make the vote countable). All participants could do "join/quit/add/reduce" freely. We can do it step by step based on the progress of DApps. It's a great start.

**Comment by jiangtao-tang** [comment]
Suggest to implement NEP-43 soon

**Comment by gjw00001** [comment]
同意，如果更短的解锁时间也可行，建议更短时间

**Comment by VieYang** [comment]
关于具体的解锁时间，以实际上线时间为基准：
- 在生效之前解锁的节点均为14天
- 在生效之后解锁的节点均为7天
- 特别的，在生效之前7天内解锁的用户，虽然生效后已变更为7天，但因为是在生效前解锁，故需要等待14天


更加NEP-40，主网上线该功能日期为3月19日，则节点解锁日期如下：
- 3月12日之前解锁：14天
- 3月12日至3月19日解锁：14天
- 3月19日之后解锁：7天
