### ISSUE TITLE
NEP-45: NewChain Ledger Node Incentive Program

### ISSUE THREAD

**Issue by VieYang** [newtonproject/NEPs#45]
---
## NEP: 45
Title: NewChain Ledger Node Incentive Program
Authors: "[Xu Jizhe](mailto:xujizhe@newtonproject.org), [Aris AC](mailto:hi@aris.ac), [Vie Yang](mailto:yangchenzhong@gmail.com)"
Discussions:
Status: Draft
Categories: Community Governance
Created: 2021-03-18

## Simple Summary

本提案描述了机器节点挖矿的具体规则。

## Abstract

申请成为机器节点的必要条件之一是创建一个社群节点且该社群节点锁仓金额需要至少10,000,000 NEW锁仓。机器节点挖矿会基于机器节点对应的的社群节点的锁仓量进行分发。

## Motivation

该NEP为了细化[NEP-40]([https://neps.newtonproject.org/neps/nep-40/](https://neps.newtonproject.org/neps/nep-40/))中提前出的机器节点挖矿。

### 机器节点参选规则

基于 [NEP-27](https://neps.newtonproject.org/neps/nep-27/)，现将机器节点参选规则描述如下，

- 在社群节点总锁仓量达到 10,000,000 NEW
    - 如果是非合伙节点，则发起人需要锁仓至少 10,000,000 NEW
    - 如果为合伙节点，则发起人与合伙人总锁仓至少 10,000,000 NEW
- 运行newchain主网机器节点

### 机器节点挖矿NEW来源

根据 [NEP-40]([https://neps.newtonproject.org/neps/nep-40/](https://neps.newtonproject.org/neps/nep-40/))，机器节点挖矿有固定 20% 的NEW，即 175026053.57892763572 NEW。

### 机器节点挖矿NEW分发规则

- 每日分发一次
- 每日NEW释放量相同
    - 每日释放量 = 总量 / 总天数
- 每日分发按照机器节点对应的社群节点的发起人的锁仓量均分
- 仅按照社群节点的发起人的锁仓量计算
    - 投票和合伙人不参与机器节点挖矿奖励分发
    - 发起人的锁仓量仅为发起人自己的锁仓量，投票和合伙人的锁仓量不计入发起人的锁仓量
- 分发时间
    - 每日分发
    - 根据UTC 0点的快照进行计算

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by arisac** [comment]
Great. I would like to narrow down the scope of this NEP to Machine Node Mining Incentives only. Since we have separate NEP for qualifications to become a Machine Node and the whole Newton Incentive Program, this one is gonna extended those NEPs focusing on how the Incentive to be used on Machine Nodes. So this NEP should not cover rules on how to become a machine node and how much NEW in the Newton Incentive Program are given to the Machine Node.

**Comment by xujizhe** [comment]
> Great. I would like to narrow down the scope of this NEP to Machine Node Mining Incentives only. Since we have separate NEP for qualifications to become a Machine Node and the whole Newton Incentive Program, this one is gonna extend those NEPs focusing on how the Incentive to be used on Machine Nodes. So this NEP should not cover rules on how to become a machine node and how much NEW in the Newton Incentive Program are given to the Machine Node.

**Comment by xujizhe** [comment]
OK, I don't think we have to write down a very specific date of implementing in NEP, or we could say it's "about" on ... or we could say the implemented date on a mission plan, that mission will quote this NEP.

**Comment by xujizhe** [comment]
> Great. I would like to narrow down the scope of this NEP to Machine Node Mining Incentives only. Since we have separate NEP for qualifications to become a Machine Node and the whole Newton Incentive Program, this one is gonna extend those NEPs focusing on how the Incentive to be used on Machine Nodes. So this NEP should not cover rules on how to become a machine node and how much NEW in the Newton Incentive Program are given to the Machine Node.

Yes, that's NEP-27, so this NEP should refer to NEP-27 also, but I think it's a good idea to explain more details in this NEP also, to make it clear to the public more.

**Comment by xujizhe** [comment]
closed?

**Comment by xujizhe** [comment]
> closed?

Sorry for my typo, and misoperation.

**Comment by VieYang** [comment]
updated.

**Comment by xujizhe** [comment]
好

**Comment by VieYang** [comment]
MainNet Reward Distribution record：
https://explorer.newtonproject.org/address/0x99cba0ab28e6024baA4A947F1Ed910f20350F49f/transactions

**Comment by VieYang** [comment]
MainNet Machie Node ming APY about:  4.998 %

**Comment by VieYang** [comment]
NEP-45: NewChain Ledger Node Incentive Program https://neps.newtonproject.org/neps/nep-45/
