### ISSUE TITLE
NEP-47: 社群节点相关参数更改

### ISSUE THREAD

**Issue by VieYang** [newtonproject/NEPs#47]
---
## NEP: 47
Title: Parameter Updates on Community Node and vote
Authors: "[Xu Jizhe](mailto:xujizhe@newtonproject.org), [Zhou Xiqiao](https://github.com/zhouxiqiao), [Vie Yang](mailto:yangchenzhong@gmail.com)"
Discussions: https://github.com/newtonproject/NEPs/issues/47
Status: Draft
Categories: Community Governance
Created: 2021-04-02
---

## Simple Summary

This proposal contains parameter changes on community node mining, including NEW staking period, mining reward calculation, and minumam lock amount.

本提案提议更改社群节点部分参数，包括锁仓时间，节点收益加成以及最小锁仓金额。

## Abstract

Changes on NewPay:
- Change NEW staking period on community node and vote.
- Change minumam lock amount on community node and vote to 10000 NEW.
- Change community node NF factor to 1, same as community vote NF factor.

在NewPay里，做如下更改：
- 更改社群节点和投票的解锁相关的时间。
- 更改社群节点（包括合伙节点和参伙人）的最小锁仓为`10000`NEW。
- 更改社群节点的锁仓所得的NewForce系数，使之与投票锁仓的NewForce系数相同。

## Motivation

NewChain MainNet ledger nodes are open to public since NEP-27 has been implemented. According to NEP-40, Newton community has more posibilities to participate in Newon ecosystem and get rewards. NEP-45 provides an incentive plan for ledger nodes to make sure the Newton network is more open and stable.

在提出NEP-27之后，NewChain MainNet节点向公众开放。 在NEP-40中提出了牛顿激励计划，该计划为社群参与牛顿生态系统创造了更多可能性，并从中受益。在NEP-45中提出了牛顿记账节点激励计划，该计划为牛顿记账节点提供激励机制，确保牛顿网络更加开放与稳定。

NEP-27, NEP-40, and NEP-45 has been implemented. This proposal is made in order to make Newton network more open and more equitable, to motivate Newton community to participate in the ledger nodes bookkeeping, liquidity mining, which are mentioned in NEP-40, and to increase the liquidity of NEW.

在NEP-27、NEP-40和NEP-45之前，通过从NewPay App参与社群节点可以使大多数社群从Newton激励计划中受益。但是在NEP-27、NEP-40和NEP-45实施之后，社群可以通过参与机器节点记账、主流币流动性挖矿和社群流动性挖矿来获得激励。为了使牛顿向更加开放更加公平更进一步，也为了社群能够更好地参与NEP-40中提到的机器节点记账、主流币流动性挖矿和社群流动性挖矿，同时为了增加NEW的流动性，特提出此提案。

The proposal is designed to reduce the complexity of the management of community nodes in the Newpay App, and enable all community members to join in the Newton Incentive Plan freely. Therefore, community participants are encouraged to use their NEW to participate in all Newton Incentive Programs, including but not limited to Newpay Community Node Mining, ledger Node Mining, and liquidity mining.

该NEP能够减少NewPay App中社区节点管理的复杂性，使所有社群用户能够更加自由的选择Newton激励计划中的项目。 因此，鼓励社区参与者使用他们的NEW来参加更多的Newton激励计划，包括但不限于NewPay社群节点挖矿、机器节点挖矿、主流币流动性挖矿和社群流动性挖矿。

### Changes on staking rules of community node and community vote

Community node vote could add or reduce staking at any time, specifically the following below:
- Allow community node owners (including partner node owners) create or quit a node at any time, add or reduce staking at any time.
- Allow community node members (including partner node members) join or quit a node at any time, add or reduce staking at any time.
- Allow community node voters vote or quit a node at any time, add or reduce staking at any time.

The following rules remain same:

- Added/reduced staking NEW is effective after 24 hours, which means the changed part of NEW will not be counted in NewForce reward.

### Changes on NEW unlock periods of community node and community vote

- Community node owners (including partner node owners) unlock period changes from 7 days to 0 day, which means unlocked NEW will be returned immediately.
- Community node members unlock period changes from 7 days to 0 day, which means unlocked NEW will be returned immediately.
- Community node voters unlock period changes from 7 days to 0 day, which means unlocked NEW will be returned immediately.
- Allow partner node owners could quit and unlock NEW at any time. The partner node will be removed when all partners quitted.

### Minimum staking amount

- Changes minimum staking amount of community node from 1000000 NEW to 10000 NEW
- Changes minimum staking amount of partner node owner from 1000000 NEW to 10000 NEW
- Changes minimum staking amount of partner node member from 1000000 NEW to 10000 NEW
- The minimum staking amount of community vote remains same as 10000 NEW

## Changes on community node mining NewForce factor

- Change community node NewForce factor from 2 to 1
- Community vote NewForce Factor remains same as 1
- Change community node additional NewForce factor from vote from 1 to 0

Explanation:

1. All staking NEW will be calculated equally. Each 10000 NEW staking everyday will get 1 NewForce.
2. The original intensions of these changes above is aligning all amounts and periods on community mining to keep it equal, simple and clear.

### 更改社群节点和投票的解锁相关的时间

允许社群节点和投票在任何时间增加或减少锁仓，涉及到如下情况：
- 允许社群节点（包括合伙节点）发起人在任何时间锁仓创建节点、增加锁仓、减少锁仓、完全解锁
- 允许合伙节点参伙人在任何时间加入合伙节点、增加锁仓、减少锁仓、完全解锁
- 允许投票人在任何时间投票、增加锁仓、减少锁仓、完全解锁

以下规则保持不变，但需要特别指出：

- 增加锁仓时被更改部分的NEW需满足24小时才能生效，即锁仓或被增仓部分的NEW在当前轮次没有NewForce收益
- 减少锁部分时被更改部分的NEW因不满24小时，所以这部分NEW在所在轮次没有NewForce收益

更改社群节点和投票的解锁相关的时间，涉及到的参数更改如下：

- 社群节点发起人解锁NEW到账时间由 `7`天改为`0`天，即社群节点发起人可以在任何时间解锁NEW或者退选且解锁的NEW立即到账
- 合伙节点发起人解锁NEW到账时间由 `7`天改为`0`天，即合伙节点发起人可以在任何时间解锁NEW且解锁的NEW立即到账
- 合伙节点参与者解锁NEW到账时间由`7`天更改为`0`天，即合伙节点参与者可以在任何时间解锁NEW或者退选且解锁的NEW立即到账
- 投票用户解锁NEW到账时间由`7`天更改为`0`天，即投票用户可以在任何时间解锁NEW且解锁的NEW立即到账
- 更改`合伙节点发起人仅当合伙节点不生效时（锁仓金额小于节点生效最小金额），才能退选以解散合伙节点` 为 `合伙节点发起人可以通过全部解锁的方式在任何时间退出合伙节点，同时在所有参伙人都退出后合伙节点会自动解散`

### 最小锁仓金额

最小锁仓金额更改如下：

- 社群节点生效的最小锁仓金额由 `1000000` NEW 更改为 `10000` NEW
- 合伙节点发起人最小锁仓金额由 `200000` NEW 更改为 `10000` NEW
- 合伙节点参伙人最小锁仓金额由 `100000` NEW 更改为 `10000` NEW
- 投票最小金额保持不变，即 `10000` NEW

### 更改社群节点的锁仓所得的NewForce系数

更改社群节点的锁仓所得的NewForce系数，涉及到如下情况：

- 社群节点锁仓 10000 NEW 每天获得的NewForce 从 `2` 更改为 `1`
- 投票锁仓 10000 NEW 每天获得的NewForce为`1`保持不变
- 投票锁仓 10000 NEW 每天给投票的节点的NewForce从`1`更改为`0`

说明：
1. 取消社群节点NF加成后，节点的NEW和投票的NEW会被平等对待，即锁仓 10000 NEW 每天均得到 1 NewForce
2. 之所以更改社群节点的NewForce系数，是因为[NEP-43](https://neps.newtonproject.org/neps/nep-43/)和本NEP中均更改了社群节点的解锁时间，使之与投票的解锁时间保持一致，以及最小门槛统一了，所以提出使社群节点锁仓和投票锁仓的NewForce系数保持一致

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by xujizhe** [comment]
Welcome to comment this proposal.

**Comment by xujizhe** [comment]
“之所以更改社群节点的NewForce系数，是因为NEP-43和本NEP中均更改了社群节点的解锁时间，使之与投票的解锁时间保持一致，所以提出使社群节点锁仓和投票锁仓的NewForce系数保持一致”

以及最小门槛统一了。

**Comment by xujizhe** [comment]
所以可以考虑“最小锁仓金额”和“更改社群节点的锁仓所得的NewForce系数”两个段落调换一下位置。

**Comment by VieYang** [comment]
已更改。

**Comment by zhouxiqiao** [comment]
English verison added. Please review and publish.
